disabled = false
languageCode = "en-gb"
languageName = "English"
weight = 1
title = "One Year of Writing"

[params]
displayName = "EN"
isoCode = "en-GB"
rtl = false
dateFormat = "2 January 2006"
logo = "logo-white.svg"
description = "Writings on Leadership and Technology"
secondaryLogo = "logo-black.svg"

[[params.author.links]]
email = "mailto:mac@oneyearofwriting.blog"
linkedin = "https://www.linkedin.com/in/macmaistrelli/"
# storygraph = "https://app.thestorygraph.com/profile/_mac_"

["params.author"]
name = "mac"
image = "rounded-portrait.png"
headline = "Leadership & Technology."
bio = "Natural scientist by training, educator by choice, and technologist by chance. Typically working in leadership. Currently on sabbatical."
email = "mac@oneyearofwriting.blog"
