[[main]]
none = "none"

[[main]]
name = "Leadership"
pageRef = "/leadership"
identifier = "7A3OrluSpd"
weight = 100

[[main]]
name = "Technology"
pageRef = "/technology"
identifier = "pXTeUzwmPO"
weight = 200

[[main]]
name = "Misc"
pageRef = "/misc"
identifier = "m1yvfYvBoj"
weight = 300

[[main]]
pre = "tag"
name = "Tags"
pageRef = "/tags"
identifier = "SRThUxDePf"
weight = 9_999

[[footer]]
none = "none"
